package persisitance.entities;
// Generated 8 oct. 2016 16:56:51 by Hibernate Tools 3.4.0.CR1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Reservation generated by hbm2java
 */
@Entity
@Table(name="reservation"
    ,catalog="agence"
)
public class Reservation  implements java.io.Serializable {


     private int idreservation;
     private Client client;
     private Hotel hotel;
     private Date dateReservation;
     private String nbrNuit;
     private String typePenssion;

    public Reservation() {
    }

	
    public Reservation(int idreservation) {
        this.idreservation = idreservation;
    }
    public Reservation(int idreservation, Client client, Hotel hotel, Date dateReservation, String nbrNuit, String typePenssion) {
       this.idreservation = idreservation;
       this.client = client;
       this.hotel = hotel;
       this.dateReservation = dateReservation;
       this.nbrNuit = nbrNuit;
       this.typePenssion = typePenssion;
    }
   
     @Id 

    
    @Column(name="idreservation", unique=true, nullable=false)
    public int getIdreservation() {
        return this.idreservation;
    }
    
    public void setIdreservation(int idreservation) {
        this.idreservation = idreservation;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="idclient")
    public Client getClient() {
        return this.client;
    }
    
    public void setClient(Client client) {
        this.client = client;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="idhotel")
    public Hotel getHotel() {
        return this.hotel;
    }
    
    public void setHotel(Hotel hotel) {
        this.hotel = hotel;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="date_reservation", length=0)
    public Date getDateReservation() {
        return this.dateReservation;
    }
    
    public void setDateReservation(Date dateReservation) {
        this.dateReservation = dateReservation;
    }

    
    @Column(name="nbr_nuit")
    public String getNbrNuit() {
        return this.nbrNuit;
    }
    
    public void setNbrNuit(String nbrNuit) {
        this.nbrNuit = nbrNuit;
    }

    
    @Column(name="type_penssion")
    public String getTypePenssion() {
        return this.typePenssion;
    }
    
    public void setTypePenssion(String typePenssion) {
        this.typePenssion = typePenssion;
    }




}


